---
title: "Causal Random Forest"
author: "Mariana Saldarriaga and Ofer Dotan"
date: "2021"
output: html_document
---

# Install packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Generalized Randon Forest (cf. Athey and Wager)
#install.packages("grf") 
```

```{r}
#Load libraries
library(haven)
library(caret)
library(tidyverse) # remember includes dplyr
library(expss)
library(summarytools)
library(mice)

```

```{r}
# Load data
ud <- read_dta("Uganda ELA Panel wide_Creation.dta")
```

# Creat subset
```{r pressure, echo=FALSE}
# Remove variables that are were used to create indexes/keep all indexes 
##removes variables that are were used to create indexes 
##keeping all indexes 
ud_subset <- ud %>% 
  subset(select = c("HHAssetvalue_total", "HHF_loanbrac", "HHM_whoshouldearn","M_ablework_if",
                    "M_children", "M_marrywhen", "M_marrywho", "M_wanttowork_if","QC_clubheard",
                    "QC_clubparticipateIMP", "QC_stillgoing", "QE_Denrolled", "Qage",
                    "Qback_school","Qhsworked_year_empl","Qhsworked_year_self", "Qincind_empl",
                    "Qincind_selfempl", "Qincome_year_ind", "QlifeskillMOREfew",
                    "QlifeskillMOREfewIMP","QlivelihoodMOREfew", "QlivelihoodMOREfewIMP", "Qoften1WEEK", "Qoften3WEEK", 
                    "Qstudy_hours", "Qworry_job", "RC_clubheard","RC_clubparticipateIMP","RC_stillgoing","RE_Denrolled", 
                    "Rage", "Rback_school", "Rhsworked_year_self", "Rhsworked_year_empl", "Rincind_empl", "Rincind_selfempl", "Rstudy_hours",
                    "Rworry_job", "age", "back_school","baseline", "branch_name", "branchno", "dist_nearclub","endline", 
                    "follow_up", "hsworked_year_empl", "hsworked_year_self", "id", "idno","incind_empl", "incind_selfempl",
                    "income_year_ind", "lifeskillMOREfew", "lifeskillMOREfewIMP","livelihoodMOREfew","livelihoodMOREfewIMP",
                    "often1WEEK","often3WEEK", "satisfaction_income", "selfempl","study_hours",
                    "treatment", "villid", "worry_job", "age_Imarry", "Rage_Imarry",          
                    "rural", "rich","below16","z_QEntrep_total", "z_Qany_iga", "z_Qselfempl", "z_Qempl","z_QExpenditure_totDF", 
                    "QM_chi","Qpart", "z_QM_chi","z_Qpart","z_QR_sexu","z_Qsex_p", "z_QRhiv_s", "z_Qalways_c", "z_Qother_c", "QM_baby_no",           
                    "QM_son", "z_Qempowerment", "z_QM_i_ageF","z_QM_i_ageM","z_QM_baby_no","z_QM_baby_ageF",       
                    "z_QM_daught", "z_QM_son","Qcontrol_body","Qaspiration","Qiga","z_REntrep_total","z_Rany_iga","z_Rselfempl","z_Rempl",               
                    "z_RExpenditure_totDF", "RM_chi", "Rpart", "RR_sexu", "Ralways_c","Rother_c","z_RM_chi",              
                    "z_Rpart", "z_RR_sexu", "z_Rsex_p", "z_RRhiv_s", "z_Ralways_c","z_Rother_c",
                    "z_Rempowerment","z_RM_i_ageF","z_RM_i_ageM","z_RM_baby_no","z_RM_baby_ageF","z_RM_daught","z_RM_son",
                    "Rcontrol_body","Raspiration","Riga", "z_Entrep_total","z_any_iga", "z_selfempl","z_empl","z_Expenditure_totDF",
                    "zALL_Entrep_total","zALL_any_iga","zALL_selfempl","zALL_empl", "zALL_Expenditure_totDF", "M_chi","part",                
                    "always_c","other_c","z_M_chi", "z_part","z_R_sexu","z_sex_p","z_Rhiv_s","z_always_c","z_other_c","zALL_R_sexu",
                    "zALL_sex_p", "zALL_Rhiv_s","zALL_always_c","zALL_other_c","z_empowerment","z_M_i_ageF","z_M_i_ageM","z_M_baby_no",
                    "z_M_baby_ageF","z_M_daught","z_M_son","zALL_empowerment","zALL_M_i_ageF","zALL_M_i_ageM", 
                    "zALL_M_baby_no","zALL_M_baby_ageF","zALL_M_daught", "zALL_M_son","control_body","aspiration", 
                    "iga","igaALL", "_Bbranch_na_2","_Bbranch_na_3","_Bbranch_na_4", "_Bbranch_na_5", "_Bbranch_na_6","_Bbranch_na_7", 
                    "_Bbranch_na_8","_Bbranch_na_9", "_Bbranch_na_10", "Attitude", "E_Denrolled")) 

# add subset attitude!

```

# Deal with missing values
```{r}
# Replace NA
ud_subset[is.na(ud_subset)] = 88

# Works NA BUT standardization some variables fail
ud_subset[ud_subset == 88] <- NA

#ud_subset_na <- na.omit(ud_subset) # Removes all NA in every row --> 0 rows

# Generates Data set with no NA -- ASK OFER
ud_subset_na <- as.data.frame(na.omit(apply(ud_subset,2,function (x) x[order(is.na(x))])))


```

# Standardization variables
```{r}
# Function to standardize variables
standardize <- function(data) {
  mean_data <- mean(data)
  sd_data <- sd(data)
  stand_data <- (data - mean_data)/sd_data
  return(stand_data)
}

# Standardize variables
ud_subset$z_hsworked_year_empl <- standardize(ud_subset$hsworked_year_empl)
ud_subset$z_Qhsworked_year_empl <- standardize(ud_subset$Qhsworked_year_empl)
ud_subset$z_Rhsworked_year_empl <- standardize(ud_subset$Rhsworked_year_empl)
ud_subset$z_satisfaction_income <- standardize(ud_subset$satisfaction_income) 
ud_subset$z_study_hours <- standardize(ud_subset$study_hours) 
ud_subset$z_Qstudy_hours <- standardize(ud_subset$Qstudy_hours) 
ud_subset$z_Rstudy_hours <- standardize(ud_subset$Rstudy_hours) 
ud_subset$z_age_Imarry <- standardize(ud_subset$age_Imarry) 
ud_subset$z_Rage_Imarry <- standardize(ud_subset$Rage_Imarry) 
ud_subset$z_M_marrywho <- standardize(ud_subset$M_marrywho)
```


```{r}
# Rename variables to use in Causal Forests (not all variables in data base)
data_uganda <- ud_subset %>% # only panel observations (not variables with ALL) # baseline and follow-up
  rename(treatment = treatment, ## baseline
         rich = rich, 
         value_assets = HHAssetvalue_total, # not make assumption, model predict
         below16 = below16, # transformation age
         age = age, # keep original values; control in paper
         branchno = branchno, # control in paper i.branch_name
         rural = rural,
         vill_id = villid, # cluster paper
         want_respect = Attitude,
         enroll_school = E_Denrolled,
         back_school = back_school,
         dist_nearclub = dist_nearclub,
         loan_brac = HHF_loanbrac, 
         att_earn_moneyfam = HHM_whoshouldearn,
         ablework_married = M_ablework_if,
         who_decidehusband = M_marrywho, 
         work_married = M_wanttowork_if, 
         index_income_gen_act = iga, # z_Entrep_total,z_any_iga,z_selfempl,z_empl,z_Expenditure_totDF
         index_aspiration = aspiration, # z_M_i_ageF,z_M_i_ageM,z_M_baby_no,z_M_baby_ageF,z_M_daught,z_M_son
         index_controlbody = control_body, # z_M_chi,z_part,z_R_sexu,z_sex_p,z_Rhiv_s,z_always_c,z_other_c
         children = z_M_chi, # -M_children(reverse), standardize dummy --> M_chi # part control over body index
         partner = z_part, # -partner, standardize dummy -->part # part control over body index
         sex_unwilling = z_R_sexu, # -R_sexunwilling, standardize dummy --> R_sexu # part control over body index
         index_empowerment = z_empowerment, # Not in aspiration index!!!!
         back_school = back_school, 
         income = income_year_ind, # already trimmed
         life_skills = lifeskillMOREfewIMP, 
         livelihood = livelihoodMOREfewIMP,
         club_sometimes = often1WEEK, 
         club_frequently = often3WEEK,
         satisf_income = satisfaction_income,
         study_hours = study_hours, 
         worry_job = worry_job, # we should inverse it 1 is not worry and this is bad, normally 1 is good
         branch_name = branch_name, # paper uses i.branch_name as control variable --> base _Bbranch_na_1 #
         foll_club_heard = RC_clubheard, ## follow up
         foll_club_part = RC_clubparticipateIMP, # imputed values
         foll_still_goclub = RC_stillgoing,
         foll_enroll_school = RE_Denrolled, 
         foll_age = Rage,
         foll_back_school = Rback_school,
         foll_study_hours = Rstudy_hours,
         foll_worry_job = Rworry_job,
         foll_children = z_RM_chi, # standardize -RM_Children (dummy), # part control over body index
         foll_partner = z_Rpart, # standardize -Rpartner (dummy) # part control over body index
         foll_sex_unwilling = z_R_sexu, # standardize -RR_sexunwilling (dummy) # part control over body index
         foll_index_income_gen_act = Riga, # z_REntrep_total,z_Rany_iga,z_Rselfempl,z_Rempl,z_RExpenditure_totDF
         foll_index_controlbody = Rcontrol_body, # z_RM_chi,z_Rpart,z_RR_sexu,z_Rsex_p,z_RRhiv_s,z_Ralways_c z_Rother_c
         foll_index_aspiration = Raspiration, # z_RM_i_ageF,z_RM_i_ageM,z_RM_baby_no,z_RM_baby_ageF,z_RM_daught,z_RM_son
         foll_index_empowerment = z_Rempowerment # Not in aspiration index!!!!
  )
  
```


```{r}
summary(data_uganda)
dim(data_uganda)
```

```{r}
##Dealing with missing values
#add a dummy variable indicating if indication is na or not
#partner
data_uganda$partner_na <- ifelse(is.na(data_uganda$partner), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(partner = replace_na(partner, 1))
#brnach no
data_uganda$branchno_na <- ifelse(is.na(data_uganda$branchno), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(branchno = replace_na(branchno, 1))
#attitude who should earn money family
data_uganda$att_earn_moneyfam_na <- ifelse(is.na(data_uganda$att_earn_moneyfam), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(att_earn_moneyfam = replace_na(att_earn_moneyfam, 1))
#enrolled in school
data_uganda$enroll_school_na <- ifelse(is.na(data_uganda$enroll_school), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(enroll_school = replace_na(enroll_school, 1))
#entrep total
data_uganda$z_Entrep_total_na <- ifelse(is.na(data_uganda$z_Entrep_total), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(z_Entrep_total = replace_na(z_Entrep_total, 1))
#expenditure total
data_uganda$z_Expenditure_totDF_na <- ifelse(is.na(data_uganda$z_Expenditure_totDF), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(z_Expenditure_totDF = replace_na(z_Expenditure_totDF, 1))
#asset value
data_uganda$value_assets_na <- ifelse(is.na(data_uganda$value_assets), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(value_assets = replace_na(value_assets, 1))
#loan brac
data_uganda$loan_brac_na <- ifelse(is.na(data_uganda$loan_brac), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(loan_brac = replace_na(loan_brac, 1))
#able to work when married
data_uganda$ablework_married_na <- ifelse(is.na(data_uganda$ablework_married), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(ablework_married = replace_na(ablework_married, 1))
# M children
data_uganda$M_children_na <- ifelse(is.na(data_uganda$M_children), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(M_children = replace_na(M_children, 1))
#marry when
data_uganda$M_marrywhen_na <- ifelse(is.na(data_uganda$M_marrywhen), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(M_marrywhen = replace_na(M_marrywhen, 1))
#who decide husband
data_uganda$who_decidehusband_na <- ifelse(is.na(data_uganda$who_decidehusband), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(who_decidehusband = replace_na(who_decidehusband, 1))

#work when married
data_uganda$work_married_na <- ifelse(is.na(data_uganda$work_married), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(work_married = replace_na(work_married, 1))

#want respect
data_uganda$want_respect_na <- ifelse(is.na(data_uganda$want_respect), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(want_respect = replace_na(want_respect, 1))

#study hours
data_uganda$study_hours_na <- ifelse(is.na(data_uganda$study_hours), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(study_hours = replace_na(study_hours, 1))

#worry job
data_uganda$worry_job_na <- ifelse(is.na(data_uganda$worry_job), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(worry_job = replace_na(worry_job, 1))

#satisfaction income
data_uganda$satisf_income_na <- ifelse(is.na(data_uganda$satisf_income), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(satisf_income = replace_na(satisf_income, 1))

#self employed
data_uganda$selfempl_na <- ifelse(is.na(data_uganda$selfempl), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(selfempl = replace_na(selfempl, 1))

#hours worked year employed
data_uganda$hsworked_year_empl_na <- ifelse(is.na(data_uganda$hsworked_year_empl), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(hsworked_year_empl = replace_na(hsworked_year_empl, 1))

#hours worked year self employed
data_uganda$hsworked_year_self_na <- ifelse(is.na(data_uganda$hsworked_year_self), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(hsworked_year_self = replace_na(hsworked_year_self, 1))

#income
data_uganda$income_na <- ifelse(is.na(data_uganda$income), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(income = replace_na(income, 1))

#index_empowerment
data_uganda$index_empowerment_na <- ifelse(is.na(data_uganda$index_empowerment), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(index_empowerment = replace_na(index_empowerment, 1))

#children
data_uganda$children_na <- ifelse(is.na(data_uganda$children), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(children = replace_na(children, 1))

#life_skills
data_uganda$life_skills_na <- ifelse(is.na(data_uganda$life_skills), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(life_skills = replace_na(life_skills, 1))

#livelihood
data_uganda$livelihood_na <- ifelse(is.na(data_uganda$livelihood), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(livelihood = replace_na(livelihood, 1))

#livelihood
data_uganda$livelihood_na <- ifelse(is.na(data_uganda$livelihood), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(livelihood = replace_na(livelihood, 1))

#rural
data_uganda$rural_na <- ifelse(is.na(data_uganda$rural), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(rural = replace_na(rural, 1))

#age
data_uganda$age_na <- ifelse(is.na(data_uganda$age), 1, 0)
data_uganda <- data_uganda %>% 
  mutate(age = replace_na(age, 1))
```


# Spliting the dataset into train and test set. Why? to not have overfiting problems. 
```{r}
## Make sure the data has no missing values (outcome and treatment to run causal forests!!!)
data_uganda_is.na <- data_uganda[!is.na(data_uganda$foll_index_income_gen_act), ]
data_uganda_na <- as_tibble(data_uganda_is.na) 

#complete cases for selected variables
data_uganda_na_o <- data_uganda %>%
  filter(complete.cases(index_empowerment,
                        foll_index_income_gen_act,# maybe here include partner (we can do an interaction with age)
                        children, 
                        partner,
                        branchno,
                        age, 
                        rural,
                        income,
                        enroll_school,
                        study_hours,  # standardization for this one not working NA
                        vill_id))


#data_uganda[complete.cases(data_uganda$index_empowerment),] #try to choose only specific columns to take the complete cases from


#data_to_split <- sample(c(FALSE, TRUE), nrow(data_uganda_na_o), replace = TRUE) #sample only rows without NAs
```


```{r}
## Datacamp method (ratio 75:25); most of causal forest use this ratio but haven't found true argument to chose this ratio. 
# Get number of rows
N <- nrow(data_uganda_na_o)
# Calculate how many rows 75% of N should be and print it; we use round to get an integer
target <- round(N * 0.80)
# Create the vector of N uniform random variables: rv
rv <- runif(N)
# Use rv to create the training set: ud_train (75% of data) and ud_test (25% of data)
data_uganda_train <- data_uganda_na_o[rv < 0.80, ]
data_uganda_test <- data_uganda_na_o[rv >= 0.80, ]
# Use nrow() to examine ud_train and ud_test
nrow(data_uganda_train)
nrow(data_uganda_test)

## I think it is large enough the data set --> we don't need cross validation to split the data!

# Other method (ratio 70:30)
set.seed(400) # To always run same answer; or just put seed
train <- sample(nrow(data_uganda_na_o), 0.7*nrow(data_uganda_na_o), replace = FALSE)
data_uganda_train_v2 <- data_uganda_na_o[train,] #  Train is like the data we would collect in a randomized experiment 
data_uganda_valid_v2 <- data_uganda_na_o[-train,] # Test would be the future cases which we are trying to predict
summary(data_uganda_train_v2)
nrow(data_uganda_train_v2)
summary(data_uganda_valid_v2)
nrow(data_uganda_valid_v2)

```

```{r}

```

### NOTES: USE CAUSAL TREE FROM GRF PACKAGE (TUNE PARAMETERS ALL)

# Train a Causal Forests
```{r}
library(grf)

# Random seed to reproduce results
set.seed

## INCOME GENERATING ACTIVITY - IGA
# Create outcome and inputs for the Causal Forests (important all numeric; including dummy code the factor variables)
Y_outcome <- as.matrix(data_uganda_train$foll_index_income_gen_act) # Vector outcome of interest
#attach outcome to train data

X_vars <- model.matrix(lm (Y_outcome ~ children + children_na +
                             branchno + branchno_na +
                             age + age_na +
                             rural + rural_na +
                             income + income_na + 
                             enroll_school + enroll_school_na +
                             study_hours+ study_hours_na + 
                             index_empowerment + index_empowerment_na +
                             enroll_school*study_hours + 
                             enroll_school_na*study_hours_na +
                             children*age +
                             children_na*age_na,
                           data = data_uganda_train)) # X is a matrix of the covariates which we are using to predict heterogeneity in treatment effect

C_vars <- data_uganda_train$vill_id


W_treatment <- as.matrix(data_uganda_train$treatment) # Treatment assignment

#train causal forest
causalforests_IGA_train <- causal_forest(X = X_vars,
                                    Y = Y_outcome,
                                    W = W_treatment, 
                                    num.trees = 5000, #more trees result in better confident intervals
                                    clusters = C_vars, # paper clusters
                                    orthog.boosting = TRUE) 
                                    # but see again!!! Athey and Wager 2019; orthogonalization

### Consider later if to add as instrument club_distance and run instrumental forest instead of causalforest

# We don't mention here Y.hat and W.hat --> Null; software silently estimates Y.hat or W.hat via regression forests.

## Predict the test data
# Tell grf to include variance estimates, and then I assign the predictions (the estimated treatment effects) to the test data frame so that we can use these in subsequent analyses
preds_IGA <- predict(
  object = causalforests_IGA_train, 
  newdata = model.matrix(~ children + children_na +
                             branchno + branchno_na +
                             age + age_na +
                             rural + rural_na +
                             income + income_na + 
                             enroll_school + enroll_school_na +
                             study_hours+ study_hours_na + 
                             index_empowerment + index_empowerment_na +
                             enroll_school*study_hours + 
                             enroll_school_na*study_hours_na +
                             children*age +
                             children_na*age_na,
                         data= data_uganda_test), 
  estimate.variance = TRUE
)

#data_uganda_test$preds_IGA <- preds_IGA$predictions[, 1]

# Estimate the conditional average treatment effect of the train model the full sample (CATE).
CATE_IGA <- average_treatment_effect(causalforests_IGA_train, target.sample = "all")

```

# Evaluate model using test/train split
```{r}
#install.packages("Metrics")
library(Metrics)

# Confusion matrix on test set
confusion_matrix <- table(data_uganda_test$foll_index_income_gen_act, preds_IGA$predictions >= 0.5)


xtab <- table(preds_IGA$predictions, data_uganda_test$foll_index_income_gen_act)
confusionMatrix(xtab)

confusionMatrix(preds_IGA$predictions, data_uganda_test$foll_index_income_gen_act)
preds_IGA$predictions

#accuracy
#?/nrow(data_uganda_test) #need to take first value from sum of confusion matrix output


#absolute error rate = 9% of the predictions are completely wrong at the moment
ae <- ae(data_uganda_test$foll_index_income_gen_act, preds_IGA$predictions)
ae


# Evaluate the rmse on both training and test data and print them
rmse_train <- rmse(causalforests_IGA_train1$predictions, data_uganda_train_v2$foll_index_income_gen_act)
rmse_train

rmse_test <- rmse(preds_IGA1$predictions, data_uganda_valid_v2$foll_index_income_gen_act)
rmse_test

```

Evaluating model performance
```{r}
library(gmodels)
#“cross tabulation indicating the agreement between the predicted and actual label vectors.” Excerpt From: Brett Lantz. “Machine Learning with R.” 
 
cross_tab <- CrossTable(x = data_uganda_test$foll_index_income_gen_act, 
                        y = preds_IGA$predictions, prop.chisq = FALSE)





```

