---
title: "Pre-processing v2"
author: "Mariana Saldarriaga"
date: "1/10/2021"
output: html_document
---

# Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(haven)
library(caret)
library(tidyverse) # remember includes dplyr
library(expss)
library(summarytools)
library(mice)

```

```{r}
# Load data
ud <- read_dta("Uganda ELA Panel wide_Creation.dta")
```

# Creat subset
```{r pressure, echo=FALSE}
# Remove variables that are were used to create indexes/keep all indexes 

# add subset attitude!

```

# Deal with missing values
```{r}
# Replace NA
ud_subset[is.na(ud_subset)] = 88

# Works NA BUT standardization some variables fail
ud_subset[ud_subset == 88] <- NA

ud_subset_na <- na.omit(ud_subset) # Removes all NA in every row --> 0 rows

# Generates Data set with no NA -- ASK OFER
ud_subset_na <- as.data.frame(na.omit(apply(ud_subset,2,function (x) x[order(is.na(x))])))
```

# Standardization variables
```{r}
# Function to standardize variables
standardize <- function(data) {
  mean_data <- mean(data)
  sd_data <- sd(data)
  stand_data <- (data - mean_data)/sd_data
  return(stand_data)
}

# Standardize variables
ud_subset$z_hsworked_year_empl <- standardize(ud_subset$hsworked_year_empl)
ud_subset$z_Qhsworked_year_empl <- standardize(ud_subset$Qhsworked_year_empl)
ud_subset$z_Rhsworked_year_empl <- standardize(ud_subset$Rhsworked_year_empl)
ud_subset$z_satisfaction_income <- standardize(ud_subset$satisfaction_income) 
ud_subset$z_study_hours <- standardize(ud_subset$study_hours) 
ud_subset$z_Qstudy_hours <- standardize(ud_subset$Qstudy_hours) 
ud_subset$z_Rstudy_hours <- standardize(ud_subset$Rstudy_hours) 
ud_subset$z_age_Imarry <- standardize(ud_subset$age_Imarry) 
ud_subset$z_Rage_Imarry <- standardize(ud_subset$Rage_Imarry) 
ud_subset$z_M_marrywho <- standardize(ud_subset$M_marrywho) 
```

# Change variables names (model)
```{r}
# qm endline
# r follow up indexes

# Missing variable attitude - baseline - desire be respected in village

# not included but in ud_subset:
## BASELINE
# "branchno", "endline", "follow_up", "z_Entrep_total", "z_Expenditure_totDF", "M_marrywhen", "z_any_iga" -> does any income activity, 
"selfempl", "z_selfempl","z_empl",   "hsworked_year_empl", "hsworked_year_self",
"incind_empl", "incind_selfempl",
"lifeskillMOREfew" "livelihoodMOREfew" -- not imputed, 
"always_c","other_c",
"igaALL"
"iga"
"z_any_iga"
"zALL_any_iga"
"zALL_Entrep_total","zALL_selfempl","zALL_empl", "zALL_Expenditure_totDF",
# igaALL = index_income_gen_act_nonpanel --> not follow up 

# "villid", "baseline",  "id", "idno",

# "age_Imarry"--> not in codebook, not sure what is it sutable age for marry other variable

# _Bbranch_na_2 = branch_2, _Bbranch_na_3 = branch_3, _Bbranch_na_4 = branch_4, _Bbranch_na_5 = branch_5,
# _Bbranch_na_6 = branch_6, _Bbranch_na_7 = branch_7, _Bbranch_na_8 = branch_8, _Bbranch_na_9 = branch_9,
# _Bbranch_na_10 = branch_10,

## Follow up
"Rhsworked_year_self", "Rhsworked_year_empl", "Rincind_empl", "Rincind_selfempl"
"Rage_Imarry", "z_REntrep_total","z_Rany_iga","z_Rselfempl","z_Rempl", "z_RExpenditure_totDF",

## ENDLINE
# "QC_clubheard", "QC_clubparticipateIMP", "QC_stillgoing", "QE_Denrolled", "Qage", "Qback_school",
                    "Qhsworked_year_empl","Qhsworked_year_self", "Qincind_empl", "Qincind_selfempl",
                    "Qincome_year_ind", "QlifeskillMOREfew", "QlifeskillMOREfewIMP","QlivelihoodMOREfew",
                    "QlivelihoodMOREfewIMP", "Qoften1WEEK", "Qoften3WEEK", "Qstudy_hours", "Qworry_job", "z_QEntrep_total", "z_Qany_iga", "z_Qselfempl", "z_Qempl","z_QExpenditure_totDF", 
                    "QM_chi","Qpart", "z_QM_chi","z_Qpart","z_QR_sexu","z_Qsex_p", "z_QRhiv_s", "z_Qalways_c", "z_Qother_c", "QM_baby_no",           
                    "QM_son", "z_Qempowerment", "z_QM_i_ageF","z_QM_i_ageM","z_QM_baby_no","z_QM_baby_ageF",      
                    "z_QM_daught", "z_QM_son","Qcontrol_body","Qaspiration","Qiga",

# Rename variables to use in Causal Forests (not all variables in data base)
data_uganda <- ud_subset %>% # only panel observations (not variables with ALL) # baseline and follow-up
  rename(treatment = treatment, ## baseline
         rich = rich, 
         value_assets = HHAssetvalue_total, # not make assumption, model predict
         below16 = below16, # transformation age
         age = age, # keep original values; control in paper
         branchno = branchno, # control in paper i.branch_name
         rural = rural,
         vill_id = villid, # cluster paper
         want_respect = Attitude,
         enroll_school = E_Denrolled,
         back_school = back_school,
         dist_nearclub = dist_nearclub,
         loan_brac = HHF_loanbrac, 
         att_earn_moneyfam = HHM_whoshouldearn,
         ablework_married = M_ablework_if,
         who_decidehusband = M_marrywho, 
         work_married = M_wanttowork_if, 
         index_income_gen_act = iga, # z_Entrep_total,z_any_iga,z_selfempl,z_empl,z_Expenditure_totDF
         index_aspiration = aspiration, # z_M_i_ageF,z_M_i_ageM,z_M_baby_no,z_M_baby_ageF,z_M_daught,z_M_son
         index_controlbody = control_body, # z_M_chi,z_part,z_R_sexu,z_sex_p,z_Rhiv_s,z_always_c,z_other_c
         children = z_M_chi, # -M_children(reverse), standardize dummy --> M_chi # part control over body index
         partner = z_part, # -partner, standardize dummy -->part # part control over body index
         sex_unwilling = z_R_sexu, # -R_sexunwilling, standardize dummy --> R_sexu # part control over body index
         index_empowerment = z_empowerment, # Not in aspiration index!!!!
         back_school = back_school, 
         income = income_year_ind, # already trimmed
         life_skills = lifeskillMOREfewIMP, 
         livelihood = livelihoodMOREfewIMP,
         club_sometimes = often1WEEK, 
         club_frequently = often3WEEK,
         satisf_income = satisfaction_income,
         study_hours = study_hours, 
         worry_job = worry_job, # we should inverse it 1 is not worry and this is bad, normally 1 is good
         branch_name = branch_name, # paper uses i.branch_name as control variable --> base _Bbranch_na_1 #
         foll_club_heard = RC_clubheard, ## follow up
         foll_club_part = RC_clubparticipateIMP, # imputed values
         foll_still_goclub = RC_stillgoing,
         foll_enroll_school = RE_Denrolled, 
         foll_age = Rage,
         foll_back_school = Rback_school,
         foll_study_hours = Rstudy_hours,
         foll_worry_job = Rworry_job,
         foll_children = z_RM_chi, # standardize -RM_Children (dummy), # part control over body index
         foll_partner = z_Rpart, # standardize -Rpartner (dummy) # part control over body index
         foll_sex_unwilling = z_R_sexu, # standardize -RR_sexunwilling (dummy) # part control over body index
         foll_index_income_gen_act = Riga, # z_REntrep_total,z_Rany_iga,z_Rselfempl,z_Rempl,z_RExpenditure_totDF
         foll_index_controlbody = Rcontrol_body, # z_RM_chi,z_Rpart,z_RR_sexu,z_Rsex_p,z_RRhiv_s,z_Ralways_c z_Rother_c
         foll_index_aspiration = Raspiration, # z_RM_i_ageF,z_RM_i_ageM,z_RM_baby_no,z_RM_baby_ageF,z_RM_daught,z_RM_son
         foll_index_empowerment = z_Rempowerment # Not in aspiration index!!!!
  )
  
```

# Create new indexes
```{r}
# To create indexes
# First, define goal and then based on the defined goal, try to find proper variables.
# Weights? See theory!


```


